package org.larder.platform.web;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import org.junit.jupiter.api.Test;

class ContractEnumConverterFactoryTest {

    /** Shape of an enum generated by openapi-generator. */
    enum LinkType {
        HELP_REQUEST("helpRequest");

        private final String value;

        LinkType(String value) {
            this.value = value;
        }

        public static LinkType fromValue(String value) {
            for (LinkType type : values()) {
                if (type.value.equals(value)) {
                    return type;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    enum Plain {
        OPEN
    }

    private final ContractEnumConverterFactory factory = new ContractEnumConverterFactory();

    @Test
    void usesTheContractSpelling() {
        assertThat(factory.getConverter(LinkType.class).convert("helpRequest")).isEqualTo(LinkType.HELP_REQUEST);
    }

    @Test
    void rejectsValuesOutsideTheContract() {
        assertThatThrownBy(() -> factory.getConverter(LinkType.class).convert("HELP_REQUEST"))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void fallsBackToTheConstantName() {
        assertThat(factory.getConverter(Plain.class).convert("OPEN")).isEqualTo(Plain.OPEN);
    }
}
