package com.cookwithus.sharing;

import com.cookwithus.domain.cook.CookId;
import com.cookwithus.domain.recipe.Ingredient;
import com.cookwithus.domain.recipe.Recipe;
import com.cookwithus.domain.recipe.RecipeId;
import com.cookwithus.infrastructure.RecipeRepository;

import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * Application service for the Sharing bounded context.
 *
 * <p>Implements the {@code publishRecipe} and {@code reviseRecipe} use cases.
 * This class is the entry point for all write operations in the Sharing context;
 * it coordinates the domain model, the repository, and — in a production system —
 * an event publisher.
 *
 * <p>Domain logic (invariant enforcement) lives in the {@link Recipe} aggregate.
 * This service is responsible for orchestration only: it does not duplicate
 * domain rules.
 *
 * <p>Scaffolding generated by AI from the Architecture Communication Canvas and
 * the Chapter 14 OpenAPI specification. Domain invariant wiring added by the team.
 */
public class SharingService {

    private final RecipeRepository recipeRepository;

    public SharingService(RecipeRepository recipeRepository) {
        this.recipeRepository = Objects.requireNonNull(recipeRepository,
                "recipeRepository must not be null");
    }

    /**
     * Publish a new Recipe authored by the given Cook.
     *
     * <p>The domain model enforces:
     * <ul>
     *   <li>title must be non-empty and at most 120 characters</li>
     *   <li>at least one Ingredient required</li>
     *   <li>each Ingredient's quantity must be positive</li>
     *   <li>at least one preparation step required</li>
     * </ul>
     *
     * @param authorId    the Cook publishing the Recipe (resolved from authentication context)
     * @param title       recipe title
     * @param description optional description
     * @param category    optional category
     * @param ingredients list of Ingredients
     * @param steps       list of preparation steps
     * @return the published Recipe
     * @throws IllegalArgumentException if any domain invariant is violated
     */
    public Recipe publishRecipe(
            CookId authorId,
            String title,
            String description,
            String category,
            List<Ingredient> ingredients,
            List<String> steps) {

        Objects.requireNonNull(authorId, "authorId must not be null");

        Recipe recipe = new Recipe(
                RecipeId.newRecipeId(),
                authorId,
                title,
                description,
                category,
                ingredients,
                steps,
                Instant.now());

        recipeRepository.save(recipe);

        // In a production system: publish RecipeShared domain event here.
        // eventPublisher.publish(new RecipeShared(recipe));

        return recipe;
    }

    /**
     * Revise a published Recipe.
     *
     * <p>Only the authoring Cook may revise their Recipe.
     * The domain model enforces authorship and all post-revision invariants.
     *
     * @param requestingCookId the Cook requesting the revision
     * @param recipeId         the identity of the Recipe to revise
     * @param newTitle         updated title
     * @param newDescription   updated description (may be null)
     * @param newIngredients   updated ingredient list
     * @param newSteps         updated preparation steps
     * @return the revised Recipe
     * @throws java.util.NoSuchElementException if the Recipe is not found
     * @throws IllegalArgumentException         if the requesting Cook is not the author,
     *                                          or if any domain invariant is violated
     */
    public Recipe reviseRecipe(
            CookId requestingCookId,
            RecipeId recipeId,
            String newTitle,
            String newDescription,
            List<Ingredient> newIngredients,
            List<String> newSteps) {

        Objects.requireNonNull(requestingCookId, "requestingCookId must not be null");
        Objects.requireNonNull(recipeId, "recipeId must not be null");

        Recipe recipe = recipeRepository.findById(recipeId)
                .orElseThrow(() -> new java.util.NoSuchElementException(
                        "Recipe not found: " + recipeId));

        recipe.revise(requestingCookId, newTitle, newDescription,
                newIngredients, newSteps, Instant.now());

        recipeRepository.save(recipe);

        // In a production system: publish RecipeRevised domain event here.
        // eventPublisher.publish(new RecipeRevised(recipe));

        return recipe;
    }
}
